Task3
iankusheva/idbetterbecoding pull request #7
Opened 2017-10-12 20:02 UTC by iankusheva

moved all db methods to a separate file
created a database smart.db for storing favourite books (consider renaming it to smth more mnemonical omg)

2017-10-13 07:16 UTC, livercat commented
А где SQL для создания табличек?

2017-10-13 07:19 UTC, iankusheva commented
аааа, sql не старый, а для создания базы книжек?

2017-10-13 07:20 UTC, livercat commented
Ага. И давай standalone_mode уберём, в будущем будет мешаться.

2017-10-13 07:31 UTC, iankusheva commented
1. т.е. я все старые методы могу смело удалить, потому что они делают не совсем то?
2. зачем мне теперь клик?
3. у меня получится основной модуль, который запустит 4 разных метода создания табличек по моей схеме? или должен быть один метод? i'm confused(((

создать дб, создать таблицу с юзерами с двумя полями, создать таблицу с авторами с двумя другими полями, создать таблицу с книгами с тремя полями, одним ссылающимся на авторов, создать таблицу с книгами юзеров с двумя FK.

какого-то франкенштейна придумываю, чесслово =/

2017-10-13 07:32 UTC, livercat commented
Ещё вещи, которые пропустил при прошлом ревью:
0) Повторюсь чтобы не потерялось: standalone_mode оказался плохой идеей, давай уберём.
1) Prompt для команды очень плохо сочетается с любой автоматизацией (например, с тестами). Вместо этого лучше сделай запуск по "click create [name] / click delete [name]".
2) Sample всё ещё плохое название.
3) Основной скрипт должен быть на верхнем уровне, не рядом с библиотеками (run_cli.py например)

2017-10-13 07:33 UTC, livercat commented
В этом таске у тебя вообще должен был быть только текстовый файлик с SQL :)

2017-10-13 07:33 UTC, livercat commented
Весь код в следующих тасках, которые я вчера завёл.

2017-10-13 07:36 UTC, iankusheva commented
поняла все, кроме второго предложения пункта 1.

2017-10-13 07:37 UTC, livercat commented
Сейчас у тебя "click -> C -> db_name". Вместо этого должна быть команда, которая сразу выполняет действие: "click create db_name", без запросов.

2017-10-13 09:41 UTC, iankusheva commented
типа для каждого действия с базой запускать скрипт заново?

пока прикреплю сюда текстовые файлы, скрипты залью как доеду до ноута.
[db.txt](https://github.com/iankusheva/idbetterbecoding/files/1382123/db.txt)
[json_string.txt](https://github.com/iankusheva/idbetterbecoding/files/1382124/json_string.txt)

2017-10-13 10:01 UTC, livercat commented
Да, заново.
JSON лучше оформить в виде key:value
```
{users:
  {<user1>: 
    {favorites:
      [{book: <name1>, author: <name1>}, {book: <name2>, author: <name2>}]
    },
  <user2>: ...
  }
}
```
В табличках хорошо бы добавить UNIQUE где это имеет смысл.

2017-10-13 10:37 UTC, iankusheva commented
как я поняла, PK уже требует UNIQUE, обновила
[db.txt](https://github.com/iankusheva/idbetterbecoding/files/1382295/db.txt)
[json_string.txt](https://github.com/iankusheva/idbetterbecoding/files/1382296/json_string.txt)

2017-10-14 19:51 UTC, livercat commented
Продолжение будет? :)

2017-10-14 20:08 UTC, iankusheva commented
будет, я не забыла! я опять не в Москве в выходные)

2017-10-14 20:11 UTC, livercat commented
Хорошо! :)

2017-10-16 19:14 UTC, iankusheva commented
1. переделала
2. у меня творческий кризис(
3. вроде положила куда нужно

2017-10-17 07:45 UTC, livercat requested changes
1) Добавить папку .idea в файлик .gitignore
2) Насчёт названия - можно исходить из того, что эта папка будет свалкой для всех модулей и тогда назвать ее common/modules/etc. Или из того, что это папка для твоего приложения, и тогда назвать её рабочим названием db_app например.

2017-10-17 07:45 UTC, livercat commented on run_cli.py
> +    if action == 'create':
Эти ифы можно заменить: http://click.pocoo.org/5/quickstart/#nesting-commands
Тогда не нужны args и будет автоматический хэлп по командам

2017-10-17 07:45 UTC, livercat commented on no_idea_how_to_name_this/db.py
> +        author = (elem['authorname'],)
Лучше здесь сделать не кортежем

2017-10-17 07:45 UTC, livercat commented on no_idea_how_to_name_this/db.py
> +        if cursor.execute('SELECT authorname FROM table_authors WHERE authorname=?', author).fetchall():
А здесь вставить author как кортеж.
И вместо select + insert можно сделать update вроде бы.

2017-10-17 07:46 UTC, livercat commented
И SQL всё ещё не положила никуда.

2017-10-17 19:28 UTC, iankusheva commented on no_idea_how_to_name_this/db.py
> +        author = (elem['authorname'],)
ох это вообще случайно сюда попало и закоммитилось, это четвертый таскать)

2017-10-17 19:39 UTC, iankusheva commented on no_idea_how_to_name_this/db.py
> +        if cursor.execute('SELECT authorname FROM table_authors WHERE authorname=?', author).fetchall():
ммм если я сделаю апдейт без where, то обновятся все строки, а если укажу where author=author, а его ещё не существует, то не вставится ничего?

2017-10-17 19:44 UTC, livercat commented on no_idea_how_to_name_this/db.py
> +        if cursor.execute('SELECT authorname FROM table_authors WHERE authorname=?', author).fetchall():
https://stackoverflow.com/questions/12105198/sqlite-how-to-get-insert-or-ignore-to-work

2017-10-17 20:14 UTC, iankusheva commented on run_cli.py
> +    if action == 'create':
это какой-то непосильный пиздец

2017-10-17 20:28 UTC, iankusheva commented on run_cli.py
> +    if action == 'create':
ладно, вроде посильный

2017-10-17 20:36 UTC, iankusheva commented
короче я UPDATE OR IGNORE запилила, но не тестила.
остальное сделала, не уверена, так ли, как ты предполагал, что я сделаю :)

2017-10-17 20:42 UTC, livercat approved these changes

2017-10-17 20:42 UTC, livercat commented on run_cli.py
> +    main()
main() не нужна, можно просто сюда cli().

2017-10-17 20:46 UTC, livercat commented
Вливай! :)

2017-10-17 20:47 UTC, merged