Task4
iankusheva/idbetterbecoding pull request #8
Opened 2017-10-22 13:30 UTC by iankusheva

here comes the ugly truth: I don't actually know any programming patterns

1. нужно ли каждое маленькое действие внутри большого метода выносить в отдельную функцию? 
2. в каком месте уместно соединиться с базой, чтобы не делать это постоянно как у меня получилось?
3. как бы эту кашу отрефакторить

p.s. старые методы забыла удалить :(

2017-10-22 14:04 UTC, livercat commented
Это придёт с опытом, не переживай.
1. Не совсем понял, что ты имеешь в виду.
2. Вынести это в context manager, который будет при открытии создавать базу если надо, открывать к ней коннекшен и возвращать курсор. При закрытии будет закрывать коннекшен. Context manager сделай двумя вариантами - классом и функцией, посмотрим какой удобнее выглядит.
3. Пока что второго пункта будет достаточно, плюс я не просто так просил тебя вынести SQL Для создания табличек в отдельный файл - чтобы не хардкодить это строчками, можно будет просто открыть файл и исполнить SQL из него. Посмотри ещё на IF NOT EXISTS, с ним можно будет прогонять создание табличек каждый раз без условия.

2017-10-22 14:07 UTC, livercat commented
4. Давай JSON всё-таки принимать снаружи, а не хардкодить в приложении. Для начала можно передавать не строчку, чтобы не заморачиваться с экранированием кавычек, а из файла:
```run_cli.py add_book --json=file_with_json.txt```
5. JSON сейчас не валидируется, это не очень хорошо. Можно для начала просто проверять, что в нём есть нужные ключи, и показывать человеческую ошибку вместо просто KeyError, который получится сейчас.

2017-10-22 14:12 UTC, livercat commented
6. Вместо
```INSERT OR IGNORE INTO table_books VALUES (NULL, ?, ?)```
лучше
```INSERT OR IGNORE INTO table_books (bookname, authorid) VALUES (?, ?)```
Так ты явно показываешь, какие поля в каком порядке идут, и нет непонятного NULL.

2017-10-22 14:14 UTC, livercat commented
Насчёт первого пункта - пока вроде большой проблемы с размером функций или с нагроможденностью логики нет, так что дробить на более мелкие рано (помимо выноса работы с коннекшеном к коонтекст менеджер).

2017-10-22 17:34 UTC, iankusheva commented
2. done
3. done, только if not exists пока записала себе в туду
4. done, вообще он принимался строкой из консоли, а переменную в скрипте я захардкодила себе для референса
5. вообще надо json схемой валидировать? может мне сразу ее накатать?
6. done

2017-10-23 07:41 UTC, livercat requested changes

2017-10-23 07:41 UTC, livercat commented on dp_app/db.py
> +class DatabaseConnection():
() можно убрать, просто
class DatabaseConnection:

2017-10-23 07:41 UTC, livercat commented on dp_app/books_only_schema.json
> +{
Схема это шикарно :)

2017-10-23 07:41 UTC, livercat commented on dp_app/db.py
> +            create_tables_in_db(self.conn)
Не очень приятное дублирование self.conn, IF NOT EXISTS поможет вообще убрать этот if.

2017-10-23 07:41 UTC, livercat commented on dp_app/db.py
> +        self.conn.close()
Лучше обернуть в try/except: pass, на случай если коннекшена нет. И в ините сделать self.conn = None, принято все переменные класса там объявлять даже если они в начале пустые.

2017-10-23 07:41 UTC, livercat commented on dp_app/db.py
> +@contextmanager
Оба варианта хороши, можешь оставить только тот, который тебе больше нравится.

2017-10-23 07:41 UTC, livercat commented on dp_app/db.py
> +    return os.path.join(running_dir, '{}'.format(dbname))
'{}'.format(dbname) можно заменить на просто dbname

2017-10-23 07:41 UTC, livercat commented on dp_app/db.py
>      cursor = conn.cursor()
Курсор обычно можно не брать, у connection тоже есть execute и commit.

2017-10-23 07:41 UTC, livercat commented on dp_app/db.py
> +    with open('/home/irina/Documents/pythonic_stuff/idbetterbecoding/dp_app/create_empty_tables_query.txt') as file_:
https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.executescript (у коннекшена такой же есть)

2017-10-25 12:57 UTC, iankusheva commented on dp_app/db.py
> +    return os.path.join(running_dir, '{}'.format(dbname))
лооооол

2017-10-25 12:57 UTC, iankusheva commented on dp_app/db.py
> +    return os.path.join(running_dir, '{}'.format(dbname))
это такой лютый индийский код получился))

2017-10-25 13:07 UTC, iankusheva commented
валидация json пока отказывается работать, ещё поразбираюсь

2017-10-25 13:34 UTC, livercat requested changes

2017-10-25 13:34 UTC, livercat commented on dp_app/db.py
> +            conn.execute(command)
executemany :)

2017-10-25 13:34 UTC, livercat commented on run_cli.py
> +    json_string = open(db.get_full_path_to_file(json_file)).read()
всегда делай with open

2017-10-25 13:34 UTC, livercat commented on run_cli.py
> +    schema = open(db.get_full_path_to_file(json_schema)).read()
with open

2017-10-25 13:34 UTC, livercat commented on run_cli.py
> +def validate_json(json_string, json_schema):
Не очень красиво, что один файл ты читаешь до вызова функции, а другой внутри.

2017-10-25 13:34 UTC, livercat commented on run_cli.py
> +def upload_user_with_books_into_db(json_file, dbname):
upload_user_with_books_into_db и upload_books_into_db начинаются одинаково - стоит вынести в отдельную функцию.

2017-10-25 14:43 UTC, iankusheva commented on dp_app/db.py
> +            conn.execute(command)
я ничего не поняль. разве executemany так умеет? я думала эта штука может типа вставить много рядов одной командой, а не выполнить много команд?

2017-10-25 14:43 UTC, iankusheva commented on run_cli.py
> +def upload_user_with_books_into_db(json_file, dbname):
всё ещё нужно вынести? там теперь всего 2 одинаковые строчки))

2017-10-25 15:32 UTC, livercat commented on dp_app/db.py
> +            conn.execute(command)
Оговорился, executescript - https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.executescript
Я выше уже давал эту ссылку.

2017-10-25 15:35 UTC, livercat requested changes

2017-10-25 15:35 UTC, livercat commented on run_cli.py
> +    with open(db.get_full_path_to_file(json_file)) as a, open(db.get_full_path_to_file(json_schema)) as b:
Что за стыдоба, "a" и "b". Лучше здесь дать нормальные имена и не заводить переменные для string_to_parse/schema, читать их прямо внутри loads.

2017-10-25 15:35 UTC, livercat commented on run_cli.py
> +def upload_user_with_books_into_db(json_file, dbname):
Теперь хорошо.

2017-10-25 15:48 UTC, iankusheva commented on dp_app/db.py
> +            conn.execute(command)
а, ну я тоже не туда читаю. поправила (все пункты поправила)

2017-10-25 15:50 UTC, livercat approved these changes

2017-10-25 15:50 UTC, livercat commented
Молодец!

2017-10-25 15:51 UTC, merged